import * as admin from 'firebase-admin'
admin.initializeApp()

export { getSimuladoQuestions } from './simulado/getSimuladoQuestions'
export { finishSimulado } from './simulado/finishSimulado'
export { getHistorico } from './historico/getHistorico'
export { getResult } from './historico/getResult'
export { getPendingCards } from './srs/getPendingCards'
export { getMateriaReviewStats } from './srs/getMateriaReviewStats'
export { reviewCard } from './srs/reviewCard'
export { getPendingCount } from './srs/getPendingCount'
export { getPixConfig } from './billing/getPixConfig'
export { submitPremiumRequest } from './billing/submitPremiumRequest'
export { deleteAllData } from './conta/deleteAllData'
export { reportQuestion } from './conta/reportQuestion'
export { registerFcmToken } from './conta/registerFcmToken'
export { getAdminDashboard } from './admin/dashboard'
export { reviewPremiumRequest } from './admin/premium'
export { setAdminRole, revokeAdminRole, listUsers, disableUser, enableUser, resetUserSrs, grantPremiumAdmin } from './admin/users'
export { createQuestion, updateQuestion, deleteQuestion } from './admin/questions'
export { getFlaggedQuestions, resolveFlaggedQuestion, deleteFlaggedQuestion } from './admin/flags'
export { createAnnouncement, updateAnnouncement, deleteAnnouncement } from './admin/announcements'
export { onPremiumRequestCreated } from './background/triggers'
export { sendReviewReminder, sendStreakReminder, sendWeeklySimuladoReminder } from './background/notifications'
